#!/bin/bash

mkdir /var/mobile/BatchomaticDebs 2>/dev/null
mkdir /var/mobile/BatchomaticDebs/UserSavedDebs 2>/dev/null
chown -R mobile /var/mobile/BatchomaticDebs
chmod -R 777 /var/mobile/BatchomaticDebs

chmod +s /usr/bin/batchomaticd
cp /Library/batchomatic/batchdeb.txt /usr/bin/batchdeb
chmod +x /usr/bin/batchdeb

chown root /Library/batchomatic/directions
chmod 755 /Library/batchomatic/directions
chown mobile /Library/batchomatic/*.sh
chmod 777 /Library/batchomatic/*.sh

exit 0
