ARCHS = armv7 arm64 arm64e

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Batchomatic

Batchomatic_FILES = Tweak.x
Batchomatic_CFLAGS = -fobjc-arc
Batchomatic_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
