#!/bin/bash

mkdir -p /var/mobile/BatchomaticDebs/UserSavedDebs
chmod -R 777 /var/mobile/BatchomaticDebs

chmod +s /usr/bin/bmd
chown root /Library/Batchomatic/directions
chmod 755 /Library/Batchomatic/directions

exit 0
